<a href="https://colab.research.google.com/github/suaJeong-777/AI-recommend-system/blob/main/%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C_%EC%88%98%EC%A0%950825.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/소개딩_2022/맥주_종류별_평점.csv', encoding='utf-8', index_col=0)
df

맥주     Aroma  Appearance    Flavor  \
0                      Kloud Original Gravity  4.292929    2.898990  4.444444   
0                      Kloud Fitz Super Clear  3.880000    2.440000  3.600000   
0                             Asahi Super Dry  3.904594    2.644624  4.336699   
0                                    Tsingtao  3.744123    2.413201  4.098553   
1                                    Heineken  3.765062    2.653520  4.281636   
..                                        ...       ...         ...       ...   
0   Berliner Kindl Jubiläums Pilsener Premium  4.918149    2.978648  5.170819   
0                  Burge Meester Shandy Lemon  4.500000    3.000000  5.000000   
0                                    Red Rock  3.200000    2.866667  3.666667   
0                   Erdinger Weissbier Dunkel  6.013616    3.708522  6.295008   
0                    Warsteiner Premium Verum  5.010284    3.006582  5.401481   

    Mouthfeel    Overall  
0    2.565657   8.808081  
0    2.080000   7.640000  
0    2.466936   8.575972  
0    2.337703   7.987342  
1    2.429712   8.460682  
..        ...        ...  
0    2.800712  10.256228  
0    2.000000   8.500000  
0    2.266667   6.400000  
0    3.245587  12.976803  
0    2.895928  10.882764  

[76 rows x 6 columns]

In [5]:
import pandas as pd
import warnings; warnings.filterwarnings('ignore')


df= pd.read_csv(r'/content/drive/MyDrive/소개딩_2022/tmdb_5000_environment.csv',encoding='cp949')

In [6]:
df

genres      id  \
0   [{"id": 6, "name": "clothes"}, {"id": 63, "nam...   19995   
1   [{"id": 6, "name": "clothes"}, {"id": 65, "nam...     285   
2   [{"id": 6, "name": "clothes"}, {"id": 63, "nam...  206647   
3   [{"id": 6, "name": "clothes"}, {"id": 63, "nam...   49026   
4   [{"id": 6, "name": "clothes"}, {"id": 61, "nam...   49529   
..                                                ...     ...   
93  [{"id": 4, "name": "kitchen"}, {"id": 44, "nam...  118340   
94  [{"id": 9, "name": "pet"}, {"id": 94, "name": ...  157336   
95  [{"id": 9, "name": "pet"}, {"id": 94, "name": ...   27205   
96  [{"id": 8, "name": "beauty"}, {"id": 82, "name...  315011   
97  [{"id": 8, "name": "beauty"}, {"id": 82, "name...   49051   

                                             keywords  \
0   [{"id": 63, "name": "bag"}, {"id": 103, "name"...   
1   [{"id": 65, "name": "pouch"}, {"id": 105, "nam...   
2   [{"id": 63, "name": "bag"}, {"id": 102, "name"...   
3   [{"id": 63, "name": "bag"}, {"id": 106, "name"...   
4   [{"id": 61, "name": "top"},  {"id": 105, "name...   
..                                                ...   
93  [{"id": 44, "name": "others"}, {"id": 106, "na...   
94  [{"id": 94, "name": "others"}, {"id": 106, "na...   
95  [{"id": 94, "name": "others"}, {"id": 106, "na...   
96  [{"id": 82, "name": "shampoo"}, {"id": 106, "n...   
97  [{"id": 82, "name": "shampoo"}, {"id": 106, "n...   

                                             overview  popularity  \
0                       bag made of abandoned plastic  150.437577   
1                         bag made of leftover fabric  139.082615   
2                     clutch made of leftover leather  107.376788   
3                          backpack made of polyester  112.312950   
4                      shirts made of leftover fabric   43.926995   
..                                                ...         ...   
93  washing soap made of lefrover fruit and vegeta...  481.098624   
94                                       soap for pet  724.247784   
95                                       soap for pet  167.583710   
96                  shampoo for vegan animal friendly    9.476999   
97                  shampoo for vegan animal friendly  108.849621   

                   title  voteAverage  voteCount  \
0                 플리츠 백팩          7.2      11800   
1                  심플파우치          6.9       4500   
2                프린트 클러치          6.3       4466   
3                     백팩          7.6       9106   
4                    오브티          6.1       2124   
..                   ...          ...        ...   
93  동구밭 풋귤 천연 설거지 비누 워싱바          7.9       9742   
94  동구밭 강아지 저자극 발비누 시어버터          8.1      10867   
95        동구밭 올바른 강아지 비누          8.1      13752   
96       동구밭 올바른 샴푸바 지성용          6.5        143   
97           동구밭 올바른 린스바          7.0       8297   

                                          imageSource  
0   https://smartstore.naver.com/blueorb/products/...  
1   https://smartstore.naver.com/blueorb/products/...  
2   https://smartstore,naver.com/blueorb/products/...  
3   https://smartstore,naver.com/blueorb/products/...  
4   https://smartstore.naver.com/blueorb/products/...  
..                                                ...  
93  https://www.donggubat.co.kr/goods/goods_view.p...  
94  https://www.donggubat.co.kr/goods/goods_view.p...  
95  https://www.donggubat.co.kr/goods/goods_view.p...  
96  https://www.donggubat.co.kr/goods/goods_view.p...  
97  https://www.donggubat.co.kr/goods/goods_view.p...  

[98 rows x 9 columns]

In [14]:
import pandas as pd
import warnings; warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

movies = pd.read_csv(r'/content/drive/MyDrive/소개딩_2022/tmdb_5000_environment.csv',encoding='cp949')
movies_df = movies[['id','title','genres','voteAverage', 'voteCount', 'popularity', 'keywords', 'overview']]

from ast import literal_eval
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)
movies_df['genres'] = movies_df['genres'].apply(lambda x : [y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [y['name'] for y in x])

from sklearn.feature_extraction.text import CountVectorizer

#CountVectorizer를 적용하기 위해 공백문자로 word단위가 구분되는 문자열로 변환.
movies_df['generes_literal'] = movies_df['genres'].apply(lambda x :  (' ').join(x))
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies_df['generes_literal'])

from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)

genre_sim_sorted_ind = genre_sim.argsort()[:,::-1]

def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    #인자로 입력된 movies_df DataFrame에서 'title'칼럼이 입력된 title_name값인 DataFrame 추출
    title_movie = df[df['title'] == title_name]

    #title_named을 가진 DataFrame의 index객체를 ndarray로 반환하고
    #sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]

    #추출된 top_n index출력, top_n index는 2차원 데이터임
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)

    return df.iloc[similar_indexes]


def movie_list(products):
  similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, products, 5)   # 찾고자 하는 데이터와 유사한 것
  return(similar_movies[['title']]) 



In [13]:
test_results= "대나무 슬리퍼"

In [11]:
movie_list(movie_list(test_results))

[[15 45 53 44  7]]
      title
15  대나무 슬리퍼
45     작두콩차
53   테이블 휴지
44      우엉차
7     대나무칫솔


In [16]:
movie_list(test_results).info()

[[15 45 53 44  7]]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 15 to 7
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   5 non-null      object
dtypes: object(1)
memory usage: 80.0+ bytes


In [17]:
result_recomment_products=movie_list(test_results).values.tolist()

[[15 45 53 44  7]]


In [15]:
movies_df

id                 title  \
0    19995                플리츠 백팩   
1      285                 심플파우치   
2   206647               프린트 클러치   
3    49026                    백팩   
4    49529                   오브티   
5      559                   수영복   
6    38757                  명함지갑   
7    99861                 대나무칫솔   
8      767                 설거지비누   
9   209112                  삼베행주   
10    1452                 소창손수건   
11   10764       제로웨이스트 셀룰로오스 행주   
12      58                  드링크백   
13   57201                 소나무볼펜   
14   49521                  티코스터   
15    2454               대나무 슬리퍼   
16   24428                  바디타올   
17    1865                 삼베마스크   
18   41154                 삼베 덮개   
19  122917              삼베 테이블매트   
20    1930                생분해 빨대   
21   20662                  풀 빨대   
22   57158             텀블러 드링크 백   
23    2268                    티백   
24     254             디쉬 앤 베지 솝   
25     597         에코백 심플네이처 숄더    
26  271110              투웨이 크로스백   
27   44833               멀티 파우치    
28  135397           호텔 커플 나이트가운   
29   37724               드라이와플가운   
30     558            드라이타올 샤워가운   
31   68721            통통 기둥 밀랍 초   
32   12155                대나무 빨대   
33   36668                대나무 칫솔   
34   62211                 설거지비누   
35    8373          비즈왁스 공기정화 캔들   
36   91314         wasara 원형접시 S   
37   68728         wasara 사각접시 L   
38  102382             wasara 볼    
39   20526             wasara 스푼   
40   49013           wasara  나이프   
41   44912             wasara 포크   
42   10193                  종이칫솔   
43     534                   비트차   
44  168259                   우엉차   
45   72190                  작두콩차   
46  127585             리프레싱 샴푸 바   
47   54138                 올인원 바   
48   81005                  비누받침   
49   64682                  튜브짜개   
50    9543                   월경컵   
51   68726               두루마리 휴지   
52   38356                  키친타올   
53     217                테이블 휴지   
54  105864           규조토볼 디퓨저 원형   
55   62177           규조토볼 디퓨저 사각   
56  188927          종이 어플리케이터 탐폰   
57   10681        논어플리케이터 디지털 탐폰   
58    5174       종이 어플리케이터 탐폰 세트   
59   14161        논어플리케이터 디지털 탐폰   
60   17979            누르 울트라씬 중형   
61  258489             누르 나이트 대형   
62     411             누르 스타터 세트   
63  246655             누르 매니아 세트   
64     155    에코어스 편안한 면 생리대 라이너   
65   14160     에코어스 편안한 면 생리대 소형   
66   15512     에코어스 편안한 면 생리대 중형   
67    1726     에코어스 편안한 면 생리대 대형   
68   44826  에코어스 편안한 면 생리대 오버나이트   
69    8487            세탁용 과탄산소다솝   
70    1735         Go on 인센스 홀더    
71  297761              Go on 꽃병   
72    2698      재생펠트 펜트레이 멜란지그레이   
73  137113       재생펠트 펜트레이 다크그레이   
74    9804         재생펠트 펜트레이 오렌지   
75   14869               PCR 펜홀더   
76  150540        스낵이즈본 노즈워크 장난감   
77  278927       럽마베베 강아지 고양이 방석   
78   10138       럽마베베 강아지 고양이 방석   
79   58595     델루나 강아지 고양이 이불&베개   
80  102651                바다를 짜요   
81  119450                지구를 짜요   
82   79698               소재저금 인형   
83   64686           꼭두서니 텐셀 스카프   
84  100402            금잔화 텐셀 스카프   
85   10192            인디고 텐셀 스카프   
86  158852             석류 텐셀 스카프   
87  177572          꼭두서니 코튼 캡 모자   
88   82690           금잔화 코튼 캡 모자   
89    5255            오거나이저 메신저백   
90   47933        75D 리사이클 3단 우산   
91   10191          75D 리사이클 장우산   
92     296           600D 롤 크로스백   
93  118340  동구밭 풋귤 천연 설거지 비누 워싱바   
94  157336  동구밭 강아지 저자극 발비누 시어버터   
95   27205        동구밭 올바른 강아지 비누   
96  315011       동구밭 올바른 샴푸바 지성용   
97   49051           동구밭 올바른 린스바   

                                          genres  voteAverage  voteCount  \
0              [clothes, bag, material, plastic]          7.2      11800   
1              [clothes, pouch, matrial, fabric]          6.9       4500   
2              [clothes, bag, material, leather]          6.3       4466   
3               [clothes, bag, material, others]          7.6       9106   
4               [clothes, top, material, fabric]          6.1  